services:
  requestpenguibackend1:
    image: benl858/request_pengui_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    
  requestpenguibackend2:
    image: benl858/request_pengui_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"  # Changed to avoid conflict
  requestpenguibackend3:
    image: benl858/request_pengui_backend
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8082:8082"